-- Pipeline: FORMULARIO → SOLICITANTE → APROVADOR → COMPLIANCE → ENCERRADO
ALTER TYPE "RequestState" ADD VALUE 'SOLICITANTE';
ALTER TYPE "RequestState" ADD VALUE 'COMPLIANCE';
ALTER TYPE "RequestState" ADD VALUE 'ENCERRADO';
